name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t opa-oidc-plugin:latest .
    - name: Tag latest
      run: docker tag opa-oidc-plugin:latest jonmclachlanatpurestorage/opa-oidc-plugin:latest
    - name: Registry Login (DockerHub)
      run: docker login --username jonmclachlanatpurestorage -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish latest
      run: docker push jonmclachlanatpurestorage/opa-oidc-plugin:latest
