name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t opa-oidc-plugin:latest .
    - name: Tag latest
      run: docker tag opa-oidc-plugin:latest docker.pkg.github.com/jonmclachlanatpurestorage/opa-oidc-plugin/opa-oidc-plugin:latest
    - name: Registry Login 
      run: docker login docker.pkg.github.com --username jonmclachlanatpurestorage -p ${{ secrets.DOCKER_REGISTRY_ACCESS_SECRETTOKEN }}
    - name: Publish
      run: docker push docker.pkg.github.com/jonmclachlanatpurestorage/opa-oidc-plugin/opa-oidc-plugin:latest
