name: Tag and Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Tag Name
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: Build image
      run: docker build -t opa-oidc-plugin:${{ env.RELEASE_VERSION }} .
    - name: Tag version
      run: docker tag opa-oidc-plugin:${{ env.RELEASE_VERSION }} jonmclachlanatpurestorage/opa-oidc-plugin:${{ env.RELEASE_VERSION }}
    - name: Registry Login (DockerHub)
      run: docker login --username jonmclachlanatpurestorage -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish RELEASE_VERSION
      run: docker push jonmclachlanatpurestorage/opa-oidc-plugin:${{ env.RELEASE_VERSION }}
